umich_catalog_indexing/bin/mindex_hathi, umich_catalog_indexing/bin/mindex_xml, umich_catalog_indexing/indexers/common.rb, umich_catalog_indexing/indexers/settings.rb
Currently, test-running subsets of the indexers is a pain because
all the configuration, `require` statements, `extend`/`include`
of macros, etc. is at the top of `commong.rb`.
This simply moves all that stuff from the top of `common.rb`
into its own file, `settings.rb`, and adds that new file
to the `mindex_*` scripts.
=> Break out configuration/requires for indexers into `settings.rb`

biblio/conf/schema.xml, biblio/conf/schema/local_explicit_fields.xml, biblio/core.properties, umich_catalog_indexing/Gemfile.lock, umich_catalog_indexing/indexers/common.rb
Adds new `author_authoritative` to drive browse.
Right now, the definition of `author` is very close to this, The subfields used in the new `to_field` are as dictated to me by Leigh Billings,  and I'm assuming (remembering?) that the selection of subfields in the current code was relatively arbitrary. 
We should pick one of the following:
* merge this in
* merge this in and later change the def of `author`
* just change the def of `author`
=> Add author_authoritative to drive author_browse

umich_catalog_indexing/Gemfile, umich_catalog_indexing/Gemfile.lock
This is essentially the same PR as #16  I just didn't want to deal with the risk of rebasing. 
Here's the comment from @billdueber from that PR:
> Somewhere along the line the format the HLB xml file provided
> by umich changed (it used to include a sub-topic tag
> and no longer does. HLB 1.0 was happily creating an
> empty lookup table with the new XML format.
> 
> Update to use high_level_browse 1.1.1 or higher.
> REQUIRES NEW GENERATION OF THE HLB LOOKUP TABLE
> with, e.g., bundle exec fetch_new_hlb <directory>
> which will put hlb.json.gz into that directory.
I've tested the updated with the `dev_solr` set of records. hlb is indeed coming through properly now.
=> updated hlb gem

mock-ht/Dockerfile, mock-ht/Gemfile, mock-ht/Gemfile.lock, umich_catalog_indexing/Dockerfile, umich_catalog_indexing/Dockerfile.prod
Adds netbase; updates mock-ht dockerfile
* per https://github.com/jruby/jruby/issues/3955 adds netbase to get rid of this warning: `WARNING: Failed to load native protocols db`
* updates mock-ht Dockerfile because it was using an old verion of node and ruby
=> Fix warning in jruby

biblio/conf/schema.xml, biblio/conf/schema/local_explicit_fields.xml, biblio/core.properties, umich_catalog_indexing/indexers/common.rb
The list of term->docCount pairs exposed by solr lists the
terms using the analyzed value; the current setup gives
a fully-normalized version (lowercase, no punctuation,
etc.) which doesn't work as a display value, needed
when the term isn't found in the Name Authority File.
This provides fields `author_authoritative_browse` (values)
and `author_authoritative_search` (search target) to get
around this limitation.
=> Fix author_authoritative browse field

umich_catalog_indexing/indexers/umich.rb
Realized the 008 field only has two digit date which will mess up sorting when there's a list of items cataloged before and after 2000. This now also handles malformed 008.
=> added Date parsing to cat_date

biblio/conf/schema.xml
The stemmer acts on the suffice `ias` but not the suffix
`ías`, causing the text type (used, e.g., in `title_common`
to treat "Ciudadanías" and "Ciudadanias" differently.
This moves the stemmer further down the analysis chain
so it isn't invoked until after diacritic suppression.
=> DNDHELP-3584 Weird diacritic mismatches

biblio/conf/schema.xml, biblio/conf/schema/local_explicit_fields.xml, biblio/core.properties
The subjects weren't being saved in such a way that it was easy to get to them with associated document counts. This changes the type to `text_facet` (which only does very basic cleanup) and indexes them.
Also, join subject parts with <space><space> instead of `|` for better sorting.
=> Store the subject fields so they can be extracted by the /term handler

biblio/conf/schema.xml, biblio/conf/schema/local_explicit_fields.xml
The `browse_match` fieldType has been changed to mirror what we're doing when generating the authorities
data, in the hopes that the number of matches reported in the browse will match the number found when you click on the link. This is currently used by author_authoritative_search, the target for links coming from the author browse.
In addition to the normal icu normalization stuff, this removes all punctuation from the analyzed string in two steps, first turning any of `-:/()[]{}=&` into spaces and then deleting everything else.
=> Unify method of normalizing text for catalog solr and browse

umich_catalog_indexing/bin/index_a_file.rb, umich_catalog_indexing/indexers/umich.rb
Indexing failed on 2022-10-14 because a community zone record had 3 `008` fields which created 3 potential cat_dates. This code forces cat_date to be the field with the biggest number.  
It also adds a convenience script to start doing an alma index for any file in the sftp directory to any solr.
=> makes sure only one cat_date is added

biblio/conf/managed-schema
The schema contains a rule that purported to collapse whitespace and didn't. Now it does.
Also be more aggressive about eliminating leading `the` for authority values.
=> Actually collapse whitespace

biblio/conf/managed-schema, biblio/conf/schema/local_explicit_fields.xml
* Add `&icu_normalization_no_case_folding;` to the `text_facet` type to avoid duplicates in facet lists (specifically author, as reported by the solr reading group.
* Add a new field, `date_of_index`, that is automatically populated when a document is added.
=> Schema: icu-normalize facets, add automatic date_of_index

biblio/conf/managed-schema, biblio/conf/schema/local_explicit_fields.xml, biblio/core.properties, umich_catalog_indexing/Gemfile.lock, umich_catalog_indexing/indexers/subject_topic.rb, umich_catalog_indexing/lib/umich_traject/subject_macros.rb
Our existing `lc_subject` field _almost_ but not quite gets us what the librarians want. This adds a new field `subject_browse` for parallel naming with `callnumber_browse` that holds all the stuff added to the subject browse index. It does basic normalization to the indexed value, as well as substitution `/\s*--\s*/ =>  " -- "`
=> Add fields and indexing rules for subject_browse

umich_catalog_indexing/lib/common/subject.rb, umich_catalog_indexing/lib/common/subject/lc_subject.rb, umich_catalog_indexing/lib/common/subject/non_lc_subject.rb, umich_catalog_indexing/spec/common/subject/lc_subject_spec.rb, umich_catalog_indexing/spec/common/subject/non_lc_subject_spec.rb, umich_catalog_indexing/spec/common/subject/subject_spec.rb
Two changes:
* An LC subject is now one that has ind2=0 PLUS it can't have a $2 that indicates it's from somewhere else. We're getting stuff from the community records that are wrong.
* A closer reading of the LoC MARC stuff indicates that non-LC are formated the same as LC. This means that NonLCSubject can just inherit from LCSubject.
=> Better subject detection and display

umich_catalog_indexing/lib/umich_traject/digital_holding.rb, umich_catalog_indexing/spec/fixtures/arborist_avd.xml, umich_catalog_indexing/spec/traject/umich/digital_holding_spec.rb
After the meeting today with the Alma Digital team, it was decided that Alma digital items should use the "label" for the description" and the "file types plus the public note" for the "source". 
I'm going to use this opportunity to have an Alma Digital item look different than an Electronic item so that I have more freedom to pass different fields in the future and so the data model is clearer.
=> Add extra fields for alma digital

umich_catalog_indexing/lib/jobs/delete_id_getter.rb
DeleteIt didn't handle basic auth which is needed for SolrCloud. Now it does.
=> fix: adds basic auth to delete action

umich_catalog_indexing/lib/jobs/delete_id_getter.rb
For the `DeleteIt` job, `SOLR_USER` and `SOLR_PASSWORD` used to be required. Now they are not required.
=> fix: solr credentials not required

umich_catalog_indexing/indexers/common.rb
I've given up for the moment on fully "fixing" all the author stuff -- I need to do a deeper dive into the stuff we're
getting from HT and via the Alma electronic resources, 'cause I'm getting some weird stuff.
Anyway, this does nothing but change the name of the field to `author_browse_terms`, which reflects what the solr config is actually expecting.
=> Use correct field 'author_browse_terms'

umich_catalog_indexing/indexers/common.rb
This fixes an (another) error introduced when renaming `author_authoritative_browse` to `author_browse_terms`, where the 1XX fields remained with the former.
=> Actually change _both_ places where we're now using author_browse_terms

biblio/Dockerfile.prod
In order to build the solr image with the jars baked in we need to update `biblio/Dockerfile.prod`
=> just load all the jars into solr

umich_catalog_indexing/indexers/common.rb
The definition of `allfields` was only going up to include 850s, so we missed all the 880s with the vernacular text in them. This is...unforgivable. The git log only goes back to Feb 2022 'cause that's when there was a big merge, but I'm sure it has been that way for-freaking-ever.
=> Change tofield("allfields") to include 880s

umich_catalog_indexing/lib/umich_traject.rb, umich_catalog_indexing/lib/umich_traject/electronic_holding.rb, umich_catalog_indexing/lib/umich_traject/holdings.rb, umich_catalog_indexing/spec/fixtures/e_resource.xml, umich_catalog_indexing/spec/indexers/umich_alma_spec.rb, umich_catalog_indexing/spec/traject/umich/electronic_holding_spec.rb
This PR Handles [LIBSEARCH-923](https://mlit.atlassian.net/browse/LIBSEARCH-923) and  [LIBSEARCH-925](https://mlit.atlassian.net/browse/LIBSEARCH-925).
It refactors the logic for handling e56 fields, adds in tests, and then adds the changes for handling these fields. 
It exposes the campuses related to e56 holdings in the `hol` json structure.
=> Libsearch 923 eresource public notes

biblio/conf/managed-schema
Simplest possible implementation, that deals with 
* byte-width normalization
* further unicode normalization to nkfc
* transliterate traditional chinese to simplified chinese
* For INDEXING ONLY, generate unigrams and bigrams from the result
*
=> Schema to allow cross-search of simplified and traditional chinese

umich_catalog_indexing/lib/umich_traject/location_map.rb
Addresses [LIBSEARCH-946](https://mlit.atlassian.net/browse/LIBSEARCH-946)
=> Libsearch 946 flint advanced search

umich_catalog_indexing/indexers/umich_alma.rb, umich_catalog_indexing/lib/ht_traject/ht_hathifiles.rb
The collection_code translation map has HTML codes for "&". This PR adds an unescape step before writing it to the solr document.
=> Fix Ampersand problem in HT source

biblio/conf/schema/local_explicit_fields.xml, umich_catalog_indexing/indexers/umich.rb, umich_catalog_indexing/indexers/umich_alma.rb, umich_catalog_indexing/lib/umich_traject.rb, umich_catalog_indexing/lib/umich_traject/availability.rb, umich_catalog_indexing/lib/umich_traject/holdings.rb, umich_catalog_indexing/spec/fixtures/hol.json, umich_catalog_indexing/spec/indexers/umich_alma_spec.rb, umich_catalog_indexing/spec/traject/umich/availability_spec.rb
Adds the field `new_availability` to the solr config. 5 states are added to this field:
* `physical`
* `hathi_trust`
* `hathi_trust_full_text`
* `hathi_trust_or_electronic_holding`
* `hathi_trust_full_text_or_electronic_holding`
These five fields account for whether or not a user wants to included HathiTrust Search only materials in their results.
=> Libsearch 955 availability filters

umich_catalog_indexing/indexers/umich_alma.rb, umich_catalog_indexing/lib/umich_traject/availability.rb
Fix to availability filters so that it works as hoped. 
Zephir holdings have keys with symbols, and alma holdings have keys with strings, so the availability class changes all of the keys to strings before passing the holding on to the methods. 
The new_availability field replaces the `acc` instead of appending to it.
=> Availability filters

umich_catalog_indexing/lib/ht_traject/ht_macros.rb, umich_catalog_indexing/spec/jobs/zephir_processing/record_spec.rb
HathiTrust records with rights code `pd-pvt` were showing as "Full Text" in Library Search. This code changes the `statusFromRights` method in HT Macros to use the same code that HathiTrust uses now to determine viewability.
=> Remove pd-pvt from ht records

umich_catalog_indexing/indexers/common.rb
Including the 4 field caused the Carousel to have wrapping problems, and we realized that it doesn't make sense to include the 4 subfield in the display anyway.
https://mlit.atlassian.net/browse/LIBSEARCH-977
=> Remove 4 from main_author_display

umich_catalog_indexing/lib/translation_maps/ht/collection_code_to_original_from.yaml
The lack of `purd` in the collection code to original form translation map broke indexing. This should fix it.
=> Hotfix: Add PURD to colllection code translation map

umich_catalog_indexing/lib/common/subjects.rb, umich_catalog_indexing/lib/common/subjects/lc_subject.rb, umich_catalog_indexing/lib/common/subjects/non_lc_subject.rb, umich_catalog_indexing/lib/common/subjects/subject.rb, umich_catalog_indexing/spec/common/subject/lc_subject_spec.rb
Addresses [LIBSEARCH-942](https://mlit.atlassian.net/browse/LIBSEARCH-942)
Changes call for a delimiter in subjects to be a call for adding padding. 
Adds 752 as a subject field and follows the [display rules](https://www.loc.gov/marc/bibliographic/bd752.html).
=> LIBSEARCH-942 adds 752 to subject field

umich_catalog_indexing/indexers/common.rb, umich_catalog_indexing/spec/common/subject/subject_spec.rb, umich_catalog_indexing/spec/common/subjects_spec.rb, umich_catalog_indexing/spec/fixtures/grudencz.xml, umich_catalog_indexing/spec/indexers/common_spec.rb, umich_catalog_indexing/spec/indexers/umich_alma_spec.rb, umich_catalog_indexing/spec/spec_helper.rb, umich_catalog_indexing/spec/traject/umich/digital_holding_spec.rb, umich_catalog_indexing/spec/traject/umich/electronic_holding_spec.rb, umich_catalog_indexing/spec/traject/umich/physical_holding_spec.rb, umich_catalog_indexing/spec/traject/umich/physical_item_spec.rb
This PR address [LIBSEARCH-944](https://mlit.atlassian.net/browse/LIBSEARCH-944)
* Tidies the specs by moving the `get_record` function into `spec_helper`.
* For the language field, this skips non control fields with a subfield 2 value. In this case the only one is 041.
The code for handling languages comes directly from the [marc21_semantics macros](https://github.com/traject/traject/blob/main/lib/traject/macros/marc21_semantics.rb).
=> Libsearch 944 language codes in 041

umich_catalog_indexing/Gemfile.lock
Sidekiq has had timeout errors for the past few days. Per: https://github.com/sidekiq/sidekiq/issues/6162 I might need to update the timeout range.
First we're trying updating sidekiq. 
ETA: an image with the latest sidekiq version ran in the reindex containers for a day, and didn't have any timeout errors. I think this is enough.
=> Fix sidekiq timeout errors

umich_catalog_indexing/lib/umich_traject/electronic_holding.rb, umich_catalog_indexing/spec/indexers/umich_alma_spec.rb, umich_catalog_indexing/spec/traject/umich/electronic_holding_spec.rb
The code for ordering electronic records sorts first based on collection name, and then based on the ranking. Sometimes collection name is nil in the record. This code makes it an empty string.
=> collection_name must be empty string not nil

umich_catalog_indexing/lib/common/subjects/lc_subject.rb, umich_catalog_indexing/spec/common/subject/lc_subject_spec.rb
All subject fields were assumed to potentially contain LC subject headings. Now only "600", "610", "611", "630", "650", "651", "655" can have LC subject headings. 
Some logs were added for special cases of subject headings with $2 lcsh or naf to see how many of those we have.
=> 653 is never lcsh

umich_catalog_indexing/lib/common/subjects.rb, umich_catalog_indexing/spec/common/subjects_spec.rb, umich_catalog_indexing/spec/fixtures/subjects/original_script_subjects.xml
We were seeing that topicStr included empty strings, which was an accessibility problem.
This was happening because the facets were treating 880s as regular Subject fields. This PR fetches the Subject tag from the $6 field and then processes it accordingly for facets.
=> LIBSEARCH-1117-deal-with-empty-topicStr

umich_catalog_indexing/indexers/umich_alma.rb, umich_catalog_indexing/lib/jobs/translation_map_generator/electronic_collections.rb, umich_catalog_indexing/lib/translation_maps/umich/electronic_collections.yaml, umich_catalog_indexing/spec/jobs/translation_map_generator/electronic_collections_spec.rb
This uses the same logic for Electronic Collections as `ElectronicHoldings`. When a single campus is present only add that. When none or both are present, add both.
=> add campuses and groups to electronic collections

umich_catalog_indexing/lib/common/subjects/lc_subject.rb
This was pretty loud last time and most of these are for community zone records. Turning this off until we can get more specific info.
=> comments out logging about subject subfields
